{
    'name': 'Odoo-WooCommerce Sync',
    'summary': """Synchronize data between WooCommerce and Odoo.""",
    'description': """Odoo-WooCommerce Sync is a connector add-on for Odoo that synchronizes data between WooCommerce and Odoo.""",
    'license': 'AGPL-3',
    'author': 'roboes',
    'website': 'https://github.com/roboes/odoo-woocommerce-sync',
    'category': 'Connectors',
    'version': '1.0',
    'depends': ['account', 'contacts', 'queue_job', 'product', 'sale_management', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/woocommerce.order.status.xml',
        'data/sequence.xml',
        'views/product_product_form.xml',
        'views/product_product_tree.xml',
        'views/product_template_form.xml',
        'views/product_template_kanban.xml',
        'views/product_template_tree.xml',
        'views/res_partner_form.xml',
        'views/res_partner_tree.xml',
        'views/sale_order_form.xml',
        'views/sale_order_tree.xml',
        'views/views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'woocommerce_sync/static/src/js/json_html_widget.js',
            'woocommerce_sync/static/src/xml/json_html_template.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
